export function operationalLabel(value: string | null | undefined): string {
  const labels: Record<string, string> = {
    draft: 'Esperando al cliente',
    confirmed: 'Confirmado',
    dispatched: 'Despachado',
    delivered: 'Entregado',
    cancelled: 'Cancelado',
    returned: 'Devuelto',
    human: 'Atención humana',
    bot: 'Automático',
    choose_size: 'Esperando talla',
    choose_reference: 'Esperando referencia',
    collect_address: 'Esperando datos de envío',
    choose_shipping: 'Esperando tipo de envío',
    confirm_order: 'Esperando confirmación',
    awaiting_size: 'Esperando talla',
    showing_models: 'Mostrando modelos',
    awaiting_name: 'Esperando nombre',
    awaiting_reuse_confirmation: 'Esperando confirmación de datos anteriores',
    awaiting_phone: 'Esperando celular',
    awaiting_department: 'Esperando departamento',
    awaiting_locality: 'Esperando municipio',
    awaiting_address: 'Esperando dirección',
    awaiting_notes: 'Esperando indicaciones',
    awaiting_shipping: 'Cotizando envío',
    awaiting_confirmation: 'Esperando confirmación',
    completed: 'Pedido confirmado',
    pending: 'Pendiente',
    processing: 'En proceso',
    created: 'Creada',
    uncertain: 'Requiere revisión',
    failed: 'Falló',
    open: 'Abierta',
    resolved: 'Resuelta',
    owner: 'Propietaria',
    operator: 'Operador',
  };
  return value === null || value === undefined
    ? 'Pendiente'
    : (labels[value] ?? 'Estado operativo');
}
