#!/usr/bin/env node
/**
 * Disposable staging smoke:
 * 1. Write .env.staging with random secrets
 * 2. Build + boot compose.prod + compose.staging
 * 3. Wait for health
 * 4. Bootstrap admin, login, hit major routes
 * 5. Confirm separate api/worker processes
 * 6. Clean shutdown
 *
 * Usage: pnpm production:smoke
 * Partial runs (no Docker / resource limits): docs/release/_task8-smoke-partial.md
 */
import { randomBytes } from 'node:crypto';
import { spawnSync } from 'node:child_process';
import { existsSync, mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { setTimeout as delay } from 'node:timers/promises';

// Staging uses Caddy `tls internal`; accept the local CA for this process only.
process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const envPath = join(root, '.env.staging');
const evidenceDir = join(root, 'docs', 'release');
const evidencePartial = join(evidenceDir, '_task8-smoke-partial.md');

const composeFiles = ['-f', 'compose.prod.yaml', '-f', 'compose.staging.yaml'];

const baseUrl = process.env.SMOKE_BASE_URL ?? 'https://localhost:18443';

function log(message) {
  console.log(`[production-smoke] ${message}`);
}

function run(command, args, options = {}) {
  return spawnSync(command, args, {
    cwd: root,
    encoding: 'utf8',
    shell: false,
    ...options,
  });
}

function requireOk(result, label) {
  if (result.status !== 0) {
    throw new Error(
      `${label} failed (exit ${result.status}): ${result.stderr || result.stdout || ''}`,
    );
  }
}

function randomSecret(bytes = 24) {
  return randomBytes(bytes).toString('base64url');
}

function writeStagingEnv() {
  const encryptionKey = randomBytes(32).toString('base64');
  const postgresPassword = `stg_${randomSecret(18)}`;
  const s3AccessKey = `stgak_${randomSecret(12)}`;
  const s3SecretKey = `stgsK_${randomSecret(24)}`;
  const adminPassword = `Adm_${randomSecret(16)}_9x`;
  const adminUsername = 'smoke-owner';

  const contents = `# Generated by scripts/production-smoke.mjs — do not commit
NODE_ENV=production
HOST=0.0.0.0
PORT=3000
LOG_LEVEL=info
CAMILA_DOMAIN=localhost
CADDY_SITE_OPTIONS=tls internal
ADMIN_ORIGIN=https://localhost:18443
MEDIA_ROOT=/data/media
STORAGE_DRIVER=s3
S3_ENDPOINT=http://minio:9000
S3_BUCKET=kairo-media-staging
S3_REGION=us-east-1
S3_ACCESS_KEY_ID=${s3AccessKey}
S3_SECRET_ACCESS_KEY=${s3SecretKey}
S3_FORCE_PATH_STYLE=true
S3_TLS_REJECT_UNAUTHORIZED=false
POSTGRES_DB=camila_staging
POSTGRES_USER=camila_staging
POSTGRES_PASSWORD=${postgresPassword}
KAIRO_CONFIG_ENCRYPTION_KEY=${encryptionKey}
SESSION_ABSOLUTE_TTL_HOURS=12
SESSION_IDLE_TTL_MINUTES=60
RETENTION_EXECUTION_ENABLED=false
WHATSAPP_GRAPH_API_VERSION=v26.0
ADMIN_BOOTSTRAP_USERNAME=${adminUsername}
ADMIN_BOOTSTRAP_PASSWORD=${adminPassword}
`;

  writeFileSync(envPath, contents, 'utf8');
  return { adminUsername, adminPassword };
}

async function waitForHealth(timeoutMs = 180_000) {
  const started = Date.now();
  let lastError = '';
  while (Date.now() - started < timeoutMs) {
    try {
      const live = await fetch(`${baseUrl}/health/live`);
      const ready = await fetch(`${baseUrl}/health/ready`);
      const admin = await fetch(`${baseUrl}/`);
      if (live.ok && ready.ok && admin.ok) {
        log('health endpoints ready');
        return;
      }
      lastError = `live=${live.status} ready=${ready.status} admin=${admin.status}`;
    } catch (error) {
      lastError = error instanceof Error ? error.message : String(error);
    }
    await delay(3_000);
  }
  const caddyLogs = run('docker', [
    'compose',
    ...composeFiles,
    '--env-file',
    '.env.staging',
    'logs',
    'caddy',
    '--tail',
    '40',
  ]);
  throw new Error(
    `Timed out waiting for health: ${lastError}\n${caddyLogs.stdout || ''}\n${caddyLogs.stderr || ''}`,
  );
}

async function checkRoutes(cookie) {
  const routes = ['/', '/login', '/orders', '/catalog'];
  for (const route of routes) {
    const response = await fetch(`${baseUrl}${route}`, {
      headers: cookie ? { cookie } : {},
    });
    if (!response.ok && response.status !== 304) {
      throw new Error(`Route ${route} returned ${response.status}`);
    }
    log(`route ok ${route} (${response.status})`);
  }
}

function confirmSeparateProcesses() {
  const apiInspect = run('docker', [
    'inspect',
    '--format',
    '{{json .Config.Cmd}}',
    'camila-prod-api-1',
  ]);
  const workerInspect = run('docker', [
    'inspect',
    '--format',
    '{{json .Config.Cmd}}',
    'camila-prod-worker-1',
  ]);
  requireOk(apiInspect, 'api process probe');
  requireOk(workerInspect, 'worker process probe');
  const apiCmd = (apiInspect.stdout || '').trim();
  const workerCmd = (workerInspect.stdout || '').trim();
  if (!apiCmd.includes('server.js')) {
    throw new Error(`API Cmd unexpected: ${apiCmd}`);
  }
  if (!workerCmd.includes('worker.js')) {
    throw new Error(`Worker Cmd unexpected: ${workerCmd}`);
  }
  if (apiCmd === workerCmd) {
    throw new Error('API and worker appear to share the same command');
  }
  log(`separate processes confirmed api=${apiCmd} worker=${workerCmd}`);
}

function writePartialEvidence(passed, detail) {
  mkdirSync(evidenceDir, { recursive: true });
  writeFileSync(
    evidencePartial,
    `# Task 8 production-smoke partial evidence

- Timestamp: ${new Date().toISOString()}
- Passed steps: ${passed.join(', ') || '(none)'}
- Detail:
\`\`\`
${detail}
\`\`\`

Docker resource limits or missing engine may prevent a full boot on this host.
`,
    'utf8',
  );
}

async function main() {
  const passed = [];
  let secrets;
  try {
    const docker = run('docker', [
      'version',
      '--format',
      '{{.Server.Version}}',
    ]);
    if (docker.status !== 0) {
      throw new Error('Docker engine not available');
    }
    passed.push('docker-available');

    secrets = writeStagingEnv();
    passed.push('env-written');
    log('wrote disposable .env.staging');

    const config = run('docker', [
      'compose',
      ...composeFiles,
      '--env-file',
      '.env.staging',
      'config',
      '--quiet',
    ]);
    requireOk(config, 'compose config');
    passed.push('compose-config');

    log('building images (migrate builds shared camila-api:local)');
    const build = run(
      'docker',
      [
        'compose',
        ...composeFiles,
        '--env-file',
        '.env.staging',
        'build',
        'migrate',
        'worker',
        'admin',
        'backup',
      ],
      { stdio: 'inherit' },
    );
    if (build.status !== 0) {
      throw new Error(`compose build failed with exit ${build.status}`);
    }
    passed.push('compose-build');

    log('starting staging stack');
    const up = run(
      'docker',
      [
        'compose',
        ...composeFiles,
        '--env-file',
        '.env.staging',
        'up',
        '-d',
        '--remove-orphans',
        '--pull',
        'missing',
      ],
      { stdio: 'inherit' },
    );
    if (up.status !== 0) {
      throw new Error(`compose up failed with exit ${up.status}`);
    }
    passed.push('compose-up');

    await waitForHealth();
    passed.push('health');

    const bootstrap = run('docker', [
      'compose',
      ...composeFiles,
      '--env-file',
      '.env.staging',
      'run',
      '--rm',
      '-T',
      '-e',
      `ADMIN_BOOTSTRAP_USERNAME=${secrets.adminUsername}`,
      '-e',
      `ADMIN_BOOTSTRAP_PASSWORD=${secrets.adminPassword}`,
      'api',
      'node',
      'dist/cli/admin-create-bootstrap.js',
    ]);
    requireOk(bootstrap, 'admin bootstrap');
    passed.push('admin-bootstrap');

    const loginResponse = await fetch(`${baseUrl}/api/admin/auth/login`, {
      method: 'POST',
      headers: {
        'content-type': 'application/json',
        origin: 'https://localhost:18443',
      },
      body: JSON.stringify({
        username: secrets.adminUsername,
        password: secrets.adminPassword,
      }),
    });
    if (!loginResponse.ok) {
      const text = await loginResponse.text();
      throw new Error(`login failed ${loginResponse.status}: ${text}`);
    }
    const setCookie = loginResponse.headers.getSetCookie?.() ?? [];
    const cookieHeader =
      setCookie.map((part) => part.split(';')[0]).join('; ') ||
      loginResponse.headers.get('set-cookie')?.split(';')[0] ||
      '';
    if (!cookieHeader) {
      throw new Error('login succeeded but no session cookie returned');
    }
    passed.push('login');
    log('login ok');

    await checkRoutes(cookieHeader);
    passed.push('routes');

    const session = await fetch(`${baseUrl}/api/admin/auth/session`, {
      headers: {
        cookie: cookieHeader,
        origin: 'https://localhost:18443',
      },
    });
    if (!session.ok) {
      throw new Error(`/api/admin/auth/session returned ${session.status}`);
    }
    passed.push('auth-session');

    confirmSeparateProcesses();
    passed.push('separate-processes');

    log('shutting down staging stack');
    const down = run(
      'docker',
      [
        'compose',
        ...composeFiles,
        '--env-file',
        '.env.staging',
        'down',
        '-v',
        '--remove-orphans',
      ],
      { stdio: 'inherit' },
    );
    requireOk(down, 'compose down');
    passed.push('shutdown');

    if (existsSync(envPath)) {
      rmSync(envPath);
    }
    if (existsSync(evidencePartial)) {
      rmSync(evidencePartial);
    }

    log(`PASS — steps: ${passed.join(' → ')}`);
  } catch (error) {
    const detail =
      error instanceof Error ? error.stack || error.message : String(error);
    writePartialEvidence(passed, detail);
    console.error(`[production-smoke] FAIL after: ${passed.join(' → ')}`);
    console.error(detail);
    run(
      'docker',
      [
        'compose',
        ...composeFiles,
        '--env-file',
        '.env.staging',
        'down',
        '-v',
        '--remove-orphans',
      ],
      { stdio: 'inherit' },
    );
    process.exitCode = 1;
  }
}

await main();
